{% set name = "trace-crispr" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/trace-crispr/trace_crispr-{{ version }}.tar.gz
  sha256: a9c7b76f8c48960867c026e047f82ef69b6015b6dba0d17ff03a5e78d1efbac1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - trace = trace_crispr.cli:cli
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=61.0
  run:
    - python >=3.9
    - click >=8.0
    - pysam >=0.20
    - pandas >=1.5
    - numpy >=1.20
    - pyyaml >=6.0
    - rapidfuzz >=3.0
    - tqdm >=4.60
    # External aligners
    - bwa >=0.7
    - bbmap >=39
    - minimap2 >=2.24
    - samtools >=1.16

test:
  imports:
    - trace_crispr
    - trace_crispr.core
    - trace_crispr.preprocessing
  commands:
    - trace --help
    - trace --version

about:
  home: https://github.com/k-roy/TRACE
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "TRACE: Triple-aligner Read Analysis for CRISPR Editing"
  description: |
    TRACE provides robust quantification of CRISPR editing outcomes
    including HDR, NHEJ, and large deletions using a triple-aligner
    consensus approach (BWA-MEM, BBMap, minimap2).
  dev_url: https://github.com/k-roy/TRACE
  doc_url: https://github.com/k-roy/TRACE

extra:
  recipe-maintainers:
    - k-roy
